name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide as much detail as you can, Thank you!
  - type: textarea
    id: description
    attributes:
      label: What's the problem?
      description: Do your best to describe the issue.
      placeholder: When I click on X from the welcome page Y happens.
      value: "Something bad..."
    validations:
      required: true
  - type: textarea
    id: expectations
    attributes:
      label: What did you expect to happen?
      description: What were you expecting to happen?
      placeholder: I thought it would be different because...
      value: "Some expectations..."
    validations:
      required: true 
  - type: textarea
    id: reproduction
    attributes:
      label: Can we reproduce the issue?
      description: What steps did you take? Add as much detail as you can. 
      placeholder: 1. Opened the app... 2. Clicked the button... 3. Computer explodes...
      value: "Some steps..."
    validations:
      required: true   
  - type: dropdown
    id: browsers
    attributes:
      label: Browser
      description: What browser are you running?
      multiple: true
      options:
        - Chrome
        - Brave
        - Firefox
        - Other
    validations:
      required: true
  - type: markdown
    id: visuals
    attributes:
      value: |
        Any images of gifs?
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://tallyho.org)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true