name: Bug Report
description: Report a bug!
title: "[Bug]: "
labels: ["bug"]
body:
  - type: checkboxes
    id: existing
    attributes:
      label: Does this issue already exist?
      options:
        - label: I could not find an existing issue for this bug
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Please provide as much detail as you can, Thank you!
  - type: textarea
    id: description
    attributes:
      label: What's the problem?
      description: Do your best to describe the issue.
      placeholder: When I click on X from the welcome page Y happens.
      value: "When I click on X from the welcome page Y happens."
    validations:
      required: true
  - type: textarea
    id: expectations
    attributes:
      label: What did you expect to happen?
      description: What were you expecting to happen?
      placeholder: I thought it would be different because...
      value: "I thought it would be different because..."
    validations:
      required: true 
  - type: textarea
    id: reproduction
    attributes:
      label: Can we reproduce the issue?
      description: What steps did you take? Add as much detail as you can. 
      placeholder: 1. Opened the app... 2. Clicked the button... 3. Computer explodes...
      value: "1. Opened the app... 2. Clicked the button... 3. Computer explodes..."
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of the extension are you running?
      options:
        - v0.18.2
        - v0.18.1
        - v0.18.0
        - v0.17.9
        - v0.17.8
        - v0.17.7
        - v0.17.6
        - v0.17.5
        - v0.17.4
        - v0.17.3
        - v0.17.2
        - v0.17.1
        - v0.17.0
        - v0.16.5
        - v0.16.4
        - v0.16.3
        - v0.16.2
        - v0.16.1
        - v0.16.0
        - v0.15.1
        - v0.15.0
        - v0.14.9
        - v0.14.8
        - v0.14.7
        - v0.14.5
        - v0.14.4
        - v0.14.3
        - v0.14.2
        - v0.14.1
        - v0.14.0
        - Community Edition v0.13.13
        - Community Edition v0.13.12
        - Community Edition v0.13.11
        - Community Edition v0.13.10
        - Community Edition v0.13.9
        - Community Edition v0.13.8
        - Community Edition v0.13.7
        - Community Edition v0.13.6
        - Community Edition v0.13.5
        - Community Edition v0.13.4
        - Community Edition v0.13.3
        - Community Edition v0.13.2
        - Community Edition v0.13.1
        - Community Edition v0.13.0
        - Community Edition v0.12.3
        - Community Edition v0.12.2
        - Community Edition v0.12.1
        - Community Edition v0.12.0
        - Community Edition v0.11.2
        - Community Edition v0.11.1
        - Community Edition v0.11.0
        - Community Edition v0.10.2
        - Community Edition v0.10.1
        - Community Edition v0.10.0
        - Community Edition v0.9.2
        - Community Edition v0.9.1
        - Community Edition v0.9.0
        - OG Edition v0.0.7
        - OG Edition v0.0.6
        - OG Edition v0.0.5
    validations:
      required: false  
  - type: dropdown
    id: browsers
    attributes:
      label: Browser
      description: What browser are you running?
      multiple: true
      options:
        - Chrome
        - Brave
        - Firefox
        - Other
    validations:
      required: true
  - type: textarea
    id: images
    attributes:
      label: Images / Gifs
      description: Can you show us visually? 
      placeholder: Drop an image here!
      value: "Drop an image or Gif here!"
    validations:
      required: true  
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://tallyho.org)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true